theme: jekyll-theme-minimal

paginate: 10
language: 'en-us'
url: 'https://inhibitor1217.github.io'
baseurl: /

title: inhibitor.log
logo: ./assets/images/logo.jpg
favicon: 

posts:
  author: inhibitor1217