theme: jekyll-theme-minimal

highlighter: rouge

paginate: 10
language: 'en-us'
url: 'https://inhibitor1217.github.io'
baseurl: /

title: inhibitor.log
logo: images/logo.jpg
favicon: images/favicon.png

author: inhibitor1217