# Permalinks
#
permalink:           pretty

# Setup
title:               inhibitor.log
tagline:             'development log'
description:         '<p>Computer Graphics, WebGL, Problem Solving</p><a href="https://github.com/inhibitor1217">GitHub Page</a>'
url:                 http://inhibitor1217.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              inhibitor
  url:               
  email:             cytops1217@gmail.com

# Custom vars
version:             1.0.0
